spring:
  profiles:
    include: route   #引入 application-route.yml 文件
  application:
    name: service-gateway # 服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848  # nacos 配置中心地址
server:
  port: 80 #网关端口