spring:
  cloud:
    gateway:
      globalcors:   # 添加全局跨域
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'

      routes:
        - id: order-route
          uri: lb://service-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/(?<segment>.*), /${segment}   # 过滤器-路径重写
            - Token=X-Response-Token, jwt  # 添加自定义过滤器-Token
        #           - AddResponseHeader=X-Response-Token-Foo, token-Bar  # 添加AddResponseHeader 过滤器
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>.*), /${segment}  # 过滤器-路径重写
        # 自定义断言规则  http://cn.bing.com?q=haha&user=li-shan
        - id: bing-route
          uri: https://cn.bing.com
          predicates:
            - name: Path
              args:
                patterns: /search
            - name: Query
              args:
                param: q
                regex: haha
            #      - Vip=user, li-shan
            - name: Vip
              args:
                param: user
                value: li-shan

      default-filters:
        - AddResponseHeader=X-Response-Default-Foo,Bar  # 全局添加响应头