spring:
  cloud:
    openfeign:
      client:
        config:
          default :  # 默认超时设置
              logger-level: full
              connect-timeout: 1000
              read-timeout: 2000
          product-feignClient :  # 指定openFeignClient超时设置
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#            request-interceptors:
#              - com.spring.order.interceptor.XTokenRequestInterceptor  # 指定单个 openFeignClient 拦截器

feign:
  sentinel:
    enabled: true   # 开启sentinel 服务熔断
