spring:
  application:
    name: seata-account
  datasource:
    url: jdbc:mysql://localhost:3306/account_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678900
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
server:
  port: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#seata:
#  data-source-proxy-mode: XA

#Log
#  logging.level.root=info
#  logging.level.cn.enn.greatgas=info
#  mybatis.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl
logging:
  level:
    root: info
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl